#!/bin/bash
# rm kintrap.out
# rm kintrap.aux
# rm kintrap.bbl
# rm kintrap.blg
# rm kintrap.log

declare -a arr=("out" "aux" "bbl" "blg" "log")
name="src"
for x in "${arr[@]}"
do
    file="$name.$x"
    if [ -f "$file" ]
    then
        rm "$file"
        echo "$file deleted."
    else
        echo "$file doesn't exist"
    fi
done
